# Auto-generated ZimaBrain app alias catalog.
# Source: local CasaOS/ZimaOS app store cache and installed apps.

APP_ALIASES = {
    '2fauth': ['2fauth'],
    'actualbudget': ['actualbudget'],
    'adguard': ['adguard', 'adguard home', 'adguardhome'],
    'adguardhome': ['adguardhome'],
    'adminer': ['adminer'],
    'albyhub': ['albyhub'],
    'alist': ['alist'],
    'alist-sync': ['alist sync', 'alist-sync', 'alistsync'],
    'anaconda3': ['anaconda3'],
    'anythingllm': ['anythingllm'],
    'archivebox': ['archivebox'],
    'audiobookshelf': ['audiobookshelf'],
    'autobrr': ['autobrr'],
    'baserow': ['baserow', 'big bear baserow', 'big-bear-baserow', 'bigbearbaserow'],
    'bazarr': ['bazarr'],
    'beaverhabittracker': ['beaverhabittracker'],
    'bili-sync': ['bili sync', 'bili-sync', 'bilisync'],
    'btop': ['big bear btop', 'big-bear-btop', 'bigbearbtop', 'btop'],
    'calibre-web': ['calibre web', 'calibre-web', 'calibreweb'],
    'chatbotui': ['chatbotui'],
    'chatgpt-next-web': ['chatgpt next web', 'chatgpt-next-web', 'chatgptnextweb'],
    'cloudbeaver': ['cloudbeaver'],
    'cloudflared': ['cloudflared'],
    'compose toolbox': ['big-bear-composetoolbox', 'compose toolbox', 'compose-toolbox', 'compose_toolbox', 'composetoolbox', 'toolbox'],
    'composetoolbox': ['big bear composetoolbox', 'big-bear-composetoolbox', 'bigbearcomposetoolbox', 'composetoolbox'],
    'convertx': ['convertx'],
    'crafty': ['crafty'],
    'databag': ['databag'],
    'ddns-go': ['ddns go', 'ddns-go', 'ddnsgo'],
    'ddns-updater': ['ddns updater', 'ddns-updater', 'ddnsupdater'],
    'deepseek-ocr': ['deepseek ocr', 'deepseek ocr_nvidia', 'deepseek-ocr', 'deepseek-ocr nvidia', 'deepseek-ocr_nvidia', 'deepseek-ocrnvidia', 'deepseekocr', 'deepseekocr_nvidia'],
    'deluge': ['deluge'],
    'dify': ['dify'],
    'docmost': ['docmost'],
    'downtify': ['downtify'],
    'duckdns': ['duckdns'],
    'duplicati': ['duplicati'],
    'emby': ['emby', 'emby nvidia', 'emby_nvidia', 'embynvidia'],
    'embystat': ['embystat'],
    'emulatorjs': ['emulatorjs'],
    'esphome': ['esphome'],
    'excalidraw': ['excalidraw'],
    'filebrowser': ['filebrowser'],
    'filedrop': ['filedrop'],
    'fileflows': ['fileflows'],
    'firefly': ['firefly'],
    'flaresolverr': ['flaresolverr'],
    'flowiseai': ['flowiseai'],
    'freshrss': ['freshrss'],
    'gateway-go': ['gateway go', 'gateway-go', 'gatewaygo'],
    'gitea': ['gitea'],
    'glances': ['glances'],
    'gopeed': ['gopeed'],
    'grafana': ['grafana'],
    'handbrake': ['handbrake'],
    'holoplay': ['holoplay'],
    'homeassistant': ['home assistant', 'home-assistant', 'homeassistant'],
    'homebridge': ['homebridge'],
    'hugo': ['hugo'],
    'immich': ['big bear immich', 'big-bear-immich', 'bigbearimmich', 'immich'],
    'jackett': ['jackett'],
    'jdownloader2': ['jdownloader2'],
    'jellyfin': ['jellyfin', 'jellyfin nvidia', 'jellyfin_nvidia', 'jellyfinnvidia'],
    'jellyseerr': ['jellyseerr'],
    'jenkin': ['jenkin'],
    'kavita': ['kavita'],
    'komga': ['komga'],
    'labelstudio': ['labelstudio'],
    'langflow': ['langflow'],
    'lazylibrarian': ['lazylibrarian'],
    'librechat': ['librechat'],
    'lidarr': ['lidarr'],
    'llama-factory': ['llama factory', 'llama factory_nvidia', 'llama-factory', 'llama-factory nvidia', 'llama-factory_nvidia', 'llama-factorynvidia', 'llamafactory', 'llamafactory_nvidia'],
    'logseq': ['logseq'],
    'lucky': ['lucky'],
    'lyrionmusicserver': ['lyrionmusicserver'],
    'mariadb': ['mariadb'],
    'maybe': ['maybe'],
    'medusa': ['medusa'],
    'memos': ['memos'],
    'mineos': ['mineos'],
    'mongo': ['mongo'],
    'mongodb4': ['mongodb4'],
    'monica': ['monica'],
    'motioneye': ['motioneye'],
    'mylar3': ['mylar3'],
    'myspeed': ['myspeed'],
    'n8n': ['n8n'],
    'navidrome': ['navidrome'],
    'netdata': ['netdata'],
    'nextcloud': ['nextcloud'],
    'nginx proxy manager': ['nginx proxy manager', 'nginx-proxy-manager', 'nginxproxymanager', 'npm'],
    'nginxproxymanager': ['nginxproxymanager'],
    'nocodb': ['nocodb'],
    'node-red': ['node red', 'node-red', 'nodered'],
    'ntfy': ['big bear ntfy', 'big-bear-ntfy', 'bigbearntfy', 'ntfy'],
    'nzbget': ['nzbget'],
    'obsidian': ['obsidian'],
    'ollama': ['ollama', 'ollama nvidia', 'ollama_nvidia', 'ollamanvidia'],
    'ombi': ['ombi'],
    'open-webui-ollama': ['open webui ollama', 'open-webui-ollama', 'openwebuiollama'],
    'openhab': ['openhab'],
    'openhands': ['openhands'],
    'openspeedtest': ['openspeedtest'],
    'openwebui': ['open web ui', 'open webui', 'open-webui', 'open-webui-ollama', 'openwebui'],
    'overseerr': ['overseerr'],
    'pdfding': ['pdfding'],
    'peaunt': ['peaunt'],
    'petio': ['petio'],
    'photoprism': ['photoprism'],
    'pihole': ['pi hole', 'pi-hole', 'pihole'],
    'pinchflat': ['pinchflat'],
    'playit-agent': ['playit agent', 'playit-agent', 'playitagent'],
    'plex': ['plex', 'plex media server', 'plex nvidia', 'plex_nvidia', 'plexmediaserver', 'plexnvidia'],
    'pocketbase': ['pocketbase'],
    'portainer': ['portainer'],
    'postgresql': ['postgresql'],
    'prowlarr': ['prowlarr'],
    'pyload': ['pyload'],
    'qbittorrent': ['qbit', 'qbitt', 'qbittorrent'],
    'radarr': ['radarr'],
    'ragflow': ['ragflow'],
    'rdtclient': ['rdtclient'],
    'readarr': ['readarr'],
    'resilio-sync': ['resilio sync', 'resilio-sync', 'resiliosync'],
    'retroarch': ['retroarch'],
    'romm': ['romm'],
    'sabnzbd': ['sabnzbd'],
    'scrutiny': ['big bear scrutiny', 'big-bear-scrutiny', 'bigbearscrutiny', 'scrutiny'],
    'sickchill': ['sickchill'],
    'siyuan-note': ['siyuan note', 'siyuan-note', 'siyuannote'],
    'smokeping': ['smokeping'],
    'snapdrop': ['snapdrop'],
    'sonarr': ['sonarr'],
    'stablediffusionwebui': ['stablediffusionwebui'],
    'stremio': ['stremio'],
    'sure': ['sure'],
    'swingmusic': ['swingmusic'],
    'syncthing': ['syncthing'],
    'tailscale': ['tailscale'],
    'taskingai': ['taskingai'],
    'tautulli': ['tautulli'],
    'teable': ['teable'],
    'threadfin': ['threadfin'],
    'transmission': ['transmission'],
    'trilium': ['trilium'],
    'ttydbridge': ['ttydbridge'],
    'tugtainer': ['big bear tugtainer', 'big-bear-tugtainer', 'bigbeartugtainer', 'tugtainer'],
    'twingate': ['twingate'],
    'unifi-controller': ['unifi controller', 'unifi-controller', 'unificontroller'],
    'unifi-network-application': ['unifi network application', 'unifi-network-application', 'unifinetworkapplication'],
    'uptimekuma': ['uptimekuma'],
    'v2raya': ['v2raya'],
    'vaultwarden': ['vaultwarden'],
    'virtualmachinemanager': ['virtualmachinemanager'],
    'vocechat': ['vocechat'],
    'wallabag': ['wallabag'],
    'webdav': ['webdav'],
    'wireguardeasy': ['wireguardeasy'],
    'zimabrain-ce': ['zimabrain ce', 'zimabrain-ce', 'zimabraince'],
    'ztnet': ['ztnet'],
}


def alias_tokens():
    words = set()
    for app, aliases in APP_ALIASES.items():
        words.add(app)
        for alias in aliases:
            words.add(alias)
            words.update(alias.replace('-', ' ').replace('_', ' ').split())
    return {w for w in words if len(w) >= 3}
